cc_binary(
  name = "Day01",
  deps = [],
  srcs = ["Day01/main.cc"],
)

cc_binary(
  name = "Day02",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day02/main.cc"],
)

cc_binary(
  name = "Day03",
  deps = [],
  srcs = ["Day03/main.cc"],
)

cc_binary(
  name = "Day04",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day04/main.cc"],
)

cc_binary(
  name = "Day05",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day05/main.cc"],
)

cc_binary(
  name = "Day06",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day06/main.cc"],
)

cc_binary(
  name = "Day07",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day07/main.cc"],
)

cc_binary(
  name = "Day08",
  deps = [],
  srcs = ["Day08/main.cc"],
)

cc_binary(
  name = "Day09",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day09/main.cc"],
)

cc_binary(
  name = "Day10",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day10/main.cc"],
)

cc_binary(
  name = "Day11",
  deps = [],
  srcs = ["Day11/main.cc"],
)

cc_binary(
  name = "Day12",
  deps = [],
  srcs = ["Day12/main.cc"],
)

cc_binary(
  name = "Day13",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day13/main.cc"],
)

cc_binary(
  name = "Day14",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day14/main.cc"],
)

cc_binary(
  name = "Day15",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day15/main.cc"],
)

cc_binary(
  name = "Day16",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day16/main.cc"],
)

cc_binary(
  name = "Day17",
  deps = [],
  srcs = ["Day17/main.cc"],
)

cc_binary(
  name = "Day18",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day18/main.cc"],
)

cc_binary(
  name = "Day19",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day19/main.cc"],
)

cc_binary(
  name = "Day20",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day20/main.cc"],
)

cc_binary(
  name = "Day21",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day21/main.cc"],
)