cc_binary(
  name = "Day01",
  deps = [],
  srcs = ["Day01/main.cc"],
)

cc_binary(
  name = "Day02",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day02/main.cc"],
)

cc_binary(
  name = "Day03",
  deps = [],
  srcs = ["Day03/main.cc"],
)

cc_binary(
  name = "Day04",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day04/main.cc"],
)

cc_binary(
  name = "Day05",
  deps = ["@com_google_absl//absl/strings"],
  srcs = ["Day05/main.cc"],
)